export enum ResMessage {
  // 200
  SUCCESS = 'SUCCESS',
  VALIDATION_FAIL = 'VALIDATION_FAIL',

  // 400
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  DUPLICATE_NICKNAME = 'DUPLICATE_NICKNAME',
  DUPLICATE_TEL = 'DUPLICATE_TEL',

  NO_EXIST_USER = 'NO_EXIST_USER',
  NO_EXIST_BOARD = 'NO_EXIST_BOARD',

  // 401
  AUTHORIZATION_FAIL = 'AUTHORIZATION_FAIL',
  SIGN_IN_FAIL = 'SIGN_IN_FAIL',

  // 403
  NO_PERMISSION = 'NO_PERMISSION',

  // 500
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DB_ERROR = 'DATABASE_ERROR',
  NOT_ALLOWED_EXTENTION = 'Only image files are allowed',
}
